<div class="flex flex-row justify-content-between">
    <img s  rc="https://scontent.fsof10-1.fna.fbcdn.net/v/t39.30808-6/330026214_2389015677941831_5154397558193039284_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=730e14&_nc_ohc=3dOjV5MtzOgAX_loUf_&tn=ul6IIsNcAr1QDJgP&_nc_ht=scontent.fsof10-1.fna&oh=00_AfA4efqip5VfqOmCfpQeYU7k4B4XxK7lRXyvUMWWKw6wEw&oe=63EC5C86" width="300px" height="100px"></img>
</div>
<href></href>
<a href="http://localhost:4200/confirm-email?hash=${recipient.hash}" class="button">Потвърдете Вашият имейл, за да използвате системата ShareMenu</a>
